"""
Crochet Ontology and Vocabulary mappings.
Includes US/UK conversions, abbreviations, stitch production/consumption rules, and descriptions.
"""

from typing import Dict, Any
from .schema import StitchType, TerminologyStandard

# US to UK terminology converter
US_TO_UK_MAP: Dict[str, str] = {
    "sl st": "sl st",
    "slip stitch": "slip stitch",
    "ch": "ch",
    "chain": "chain",
    "sc": "dc",
    "single crochet": "double crochet",
    "hdc": "htr",
    "half double crochet": "half treble",
    "dc": "tr",
    "double crochet": "treble crochet",
    "tr": "dtr",
    "treble crochet": "double treble",
    "triple crochet": "double treble",
    "dtr": "trtr",
    "double treble": "triple treble",
}

UK_TO_US_MAP: Dict[str, str] = {v: k for k, v in US_TO_UK_MAP.items()}

# Stitch metadata: base stitches consumed (target_stitch_count) and stitches created (produced_stitch_count)
# and default symbol representation
STITCH_METADATA: Dict[StitchType, Dict[str, Any]] = {
    StitchType.CH: {
        "name": "Chain",
        "us_abbr": "ch",
        "uk_abbr": "ch",
        "consumed": 0,
        "produced": 1,
        "height_units": 0.5,
        "symbol": "chain_oval",
        "category": "basic",
        "description": "Yarn over, pull through loop on hook",
    },
    StitchType.SL_ST: {
        "name": "Slip Stitch",
        "us_abbr": "sl st",
        "uk_abbr": "sl st",
        "consumed": 1,
        "produced": 0,
        "height_units": 0.2,
        "symbol": "slip_stitch_dot",
        "category": "basic",
        "description": "Insert hook in st, YO, pull through st and loop on hook",
    },
    StitchType.SC: {
        "name": "Single Crochet",
        "us_abbr": "sc",
        "uk_abbr": "dc",
        "consumed": 1,
        "produced": 1,
        "height_units": 1.0,
        "symbol": "sc_plus",
        "category": "basic",
        "description": "Insert hook, YO, pull through, YO, pull through 2 loops",
    },
    StitchType.HDC: {
        "name": "Half Double Crochet",
        "us_abbr": "hdc",
        "uk_abbr": "htr",
        "consumed": 1,
        "produced": 1,
        "height_units": 1.5,
        "symbol": "hdc_tee",
        "category": "basic",
        "description": "YO, insert hook, YO, pull through, YO, pull through all 3 loops",
    },
    StitchType.DC: {
        "name": "Double Crochet",
        "us_abbr": "dc",
        "uk_abbr": "tr",
        "consumed": 1,
        "produced": 1,
        "height_units": 2.0,
        "symbol": "dc_cross",
        "category": "basic",
        "description": "YO, insert hook, YO, pull through, [YO, pull through 2 loops] twice",
    },
    StitchType.TR: {
        "name": "Treble Crochet",
        "us_abbr": "tr",
        "uk_abbr": "dtr",
        "consumed": 1,
        "produced": 1,
        "height_units": 3.0,
        "symbol": "tr_double_cross",
        "category": "basic",
        "description": "YO twice, insert hook, pull through, [YO, pull through 2 loops] 3 times",
    },
    StitchType.DTR: {
        "name": "Double Treble Crochet",
        "us_abbr": "dtr",
        "uk_abbr": "trtr",
        "consumed": 1,
        "produced": 1,
        "height_units": 4.0,
        "symbol": "dtr_triple_cross",
        "category": "basic",
        "description": "YO 3 times, insert hook, pull through, [YO, pull through 2 loops] 4 times",
    },
    StitchType.MAGIC_RING: {
        "name": "Magic Ring",
        "us_abbr": "mr",
        "uk_abbr": "mr",
        "consumed": 0,
        "produced": 0,
        "height_units": 0.0,
        "symbol": "magic_ring_loop",
        "category": "foundation",
        "description": "Adjustable loop for working stitches in the round",
    },
    StitchType.FOUNDATION_CH: {
        "name": "Foundation Chain",
        "us_abbr": "fch",
        "uk_abbr": "fch",
        "consumed": 0,
        "produced": 1,
        "height_units": 0.5,
        "symbol": "chain_oval",
        "category": "foundation",
        "description": "Initial base chain",
    },
    StitchType.INC: {
        "name": "Single Crochet Increase",
        "us_abbr": "inc",
        "uk_abbr": "2 dc inc",
        "consumed": 1,
        "produced": 2,
        "height_units": 1.0,
        "symbol": "sc_inc_v",
        "category": "increase",
        "description": "2 single crochets worked in the same base stitch",
    },
    StitchType.DC_INC: {
        "name": "Double Crochet Increase",
        "us_abbr": "dc inc",
        "uk_abbr": "2 tr inc",
        "consumed": 1,
        "produced": 2,
        "height_units": 2.0,
        "symbol": "dc_inc_v",
        "category": "increase",
        "description": "2 double crochets worked in the same base stitch",
    },
    StitchType.HDC_INC: {
        "name": "Half Double Crochet Increase",
        "us_abbr": "hdc inc",
        "uk_abbr": "2 htr inc",
        "consumed": 1,
        "produced": 2,
        "height_units": 1.5,
        "symbol": "hdc_inc_v",
        "category": "increase",
        "description": "2 half double crochets worked in the same base stitch",
    },
    StitchType.DEC: {
        "name": "Single Crochet Decrease",
        "us_abbr": "dec / sc2tog",
        "uk_abbr": "dc2tog",
        "consumed": 2,
        "produced": 1,
        "height_units": 1.0,
        "symbol": "sc_dec_inv_v",
        "category": "decrease",
        "description": "2 single crochets joined together over 2 base stitches",
    },
    StitchType.DC_DEC: {
        "name": "Double Crochet Decrease",
        "us_abbr": "dc2tog / dc dec",
        "uk_abbr": "tr2tog",
        "consumed": 2,
        "produced": 1,
        "height_units": 2.0,
        "symbol": "dc_dec_inv_v",
        "category": "decrease",
        "description": "2 double crochets joined together over 2 base stitches",
    },
    StitchType.HDC_DEC: {
        "name": "Half Double Crochet Decrease",
        "us_abbr": "hdc2tog / hdc dec",
        "uk_abbr": "htr2tog",
        "consumed": 2,
        "produced": 1,
        "height_units": 1.5,
        "symbol": "hdc_dec_inv_v",
        "category": "decrease",
        "description": "2 half double crochets joined together over 2 base stitches",
    },
    StitchType.INV_DEC: {
        "name": "Invisible Decrease",
        "us_abbr": "inv dec",
        "uk_abbr": "inv dec",
        "consumed": 2,
        "produced": 1,
        "height_units": 1.0,
        "symbol": "sc_dec_inv_v",
        "category": "decrease",
        "description": "Invisible decrease worked through front loops only",
    },
    StitchType.PUFF: {
        "name": "Puff Stitch",
        "us_abbr": "puff",
        "uk_abbr": "puff",
        "consumed": 1,
        "produced": 1,
        "height_units": 2.0,
        "symbol": "puff_oval",
        "category": "textured",
        "description": "Multiple yarn-over loops pulled up in same st and closed together",
    },
    StitchType.POPCORN: {
        "name": "Popcorn Stitch",
        "us_abbr": "popcorn / pc",
        "uk_abbr": "popcorn",
        "consumed": 1,
        "produced": 1,
        "height_units": 2.2,
        "symbol": "popcorn_cluster",
        "category": "textured",
        "description": "5 dc worked in same stitch, hook dropped and reinserted to cinch into bulb",
    },
    StitchType.BOBBLE: {
        "name": "Bobble Stitch",
        "us_abbr": "bobble / bo",
        "uk_abbr": "bobble",
        "consumed": 1,
        "produced": 1,
        "height_units": 2.0,
        "symbol": "bobble_cluster",
        "category": "textured",
        "description": "Several partial dc worked into same st and closed together with 1 YO",
    },
    StitchType.CLUSTER: {
        "name": "Cluster Stitch",
        "us_abbr": "cluster / cl",
        "uk_abbr": "cluster",
        "consumed": 1,
        "produced": 1,
        "height_units": 2.0,
        "symbol": "cluster_symbol",
        "category": "textured",
        "description": "Cluster of stitches worked together",
    },
    StitchType.PICOT: {
        "name": "Picot Stitch",
        "us_abbr": "picot",
        "uk_abbr": "picot",
        "consumed": 0,
        "produced": 1,
        "height_units": 1.0,
        "symbol": "picot_triangle",
        "category": "decorative",
        "description": "Ch 3, sl st into first ch or base st",
    },
    StitchType.SKIP: {
        "name": "Skip Stitch",
        "us_abbr": "sk",
        "uk_abbr": "miss / sk",
        "consumed": 1,
        "produced": 0,
        "height_units": 0.0,
        "symbol": "skip_dash",
        "category": "structural",
        "description": "Skip indicated number of base stitches",
    },
    StitchType.SPACE: {
        "name": "Chain Space",
        "us_abbr": "ch-sp",
        "uk_abbr": "ch-sp",
        "consumed": 0,
        "produced": 1,
        "height_units": 0.5,
        "symbol": "space_bracket",
        "category": "structural",
        "description": "Space formed by previous chain",
    },
    StitchType.JOIN: {
        "name": "Join Round",
        "us_abbr": "sl st to join",
        "uk_abbr": "sl st to join",
        "consumed": 0,
        "produced": 0,
        "height_units": 0.0,
        "symbol": "join_arrow",
        "category": "structural",
        "description": "Join to first stitch of round with slip stitch",
    },
    StitchType.TURN: {
        "name": "Turn Work",
        "us_abbr": "turn",
        "uk_abbr": "turn",
        "consumed": 0,
        "produced": 0,
        "height_units": 0.0,
        "symbol": "turn_curl",
        "category": "structural",
        "description": "Turn work to begin next row",
    },
}
